name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build jar
        run: ./mvnw package -DskipTests

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-north-1
          application_name: spring-boot-0
          environment_name: spring-boot-0-env
          version_label: ${{ github.sha }}
          deployment_package: target/spring-boot-0-0.0.1-SNAPSHOT.jar